/*
 * app_GPIO.h
 *
 *  Created on: 10/09/2017
 *      Author: OmarSevilla
 */

#ifndef APP_GPIO_H_
#define APP_GPIO_H_
#include "MKL25Z4.h"
#include "fsl_gpio.h"

/* Macros for LED GREEN */
#define LED_RED_GPIO_BASE		GPIOB
#define LED_RED_PORT_BASE		PORTB
#define LED_RED_PIN_NUMBER		18U

/* Macros for LED GREEN */
#define LED_GREEN_GPIO_BASE		GPIOB
#define LED_GREEN_PORT_BASE		PORTB
#define LED_GREEN_PIN_NUMBER	19U

/* Macros for LED GREEN */
#define LED_BLUE_GPIO_BASE		GPIOD
#define LED_BLUE_PORT_BASE		PORTD
#define LED_BLUE_PIN_NUMBER		1U

/* LED MACROS */
#define LED_RED_OFF()		GPIO_SetPinsOutput(LED_RED_GPIO_BASE, (1U << LED_RED_PIN_NUMBER))
#define LED_GREEN_OFF()		GPIO_SetPinsOutput(LED_GREEN_GPIO_BASE, (1U << LED_GREEN_PIN_NUMBER))
#define LED_BLUE_OFF()		GPIO_SetPinsOutput(LED_BLUE_GPIO_BASE, (1U << LED_BLUE_PIN_NUMBER))

#define LED_RED_ON()		GPIO_ClearPinsOutput(LED_RED_GPIO_BASE, (1U << LED_RED_PIN_NUMBER))
#define LED_GREEN_ON()		GPIO_ClearPinsOutput(LED_GREEN_GPIO_BASE, (1U << LED_GREEN_PIN_NUMBER))
#define LED_BLUE_ON()		GPIO_ClearPinsOutput(LED_BLUE_GPIO_BASE, (1U << LED_BLUE_PIN_NUMBER))

#define LED_RED_TOGGLE()	GPIO_TogglePinsOutput(LED_RED_GPIO_BASE, (1U << LED_RED_PIN_NUMBER))
#define LED_GREEN_TOGGLE()	GPIO_TogglePinsOutput(LED_GREEN_GPIO_BASE, (1U << LED_GREEN_PIN_NUMBER))
#define LED_BLUE_TOGGLE()	GPIO_TogglePinsOutput(LED_BLUE_GPIO_BASE, (1U << LED_BLUE_PIN_NUMBER))

#define LED_RED_GET_STATE()		GPIO_ReadPinInput(LED_RED_GPIO_BASE, (LED_RED_PIN_NUMBER))
#define LED_GREEN_GET_STATE()	GPIO_ReadPinInput(LED_GREEN_GPIO_BASE, (LED_GREEN_PIN_NUMBER))
#define LED_BLUE_GET_STATE()	GPIO_ReadPinInput(LED_BLUE_GPIO_BASE, (LED_BLUE_PIN_NUMBER))

#define LED_RED_SET_STATE(state)	GPIO_WritePinOutput(LED_RED_GPIO_BASE, (LED_RED_PIN_NUMBER),state)
#define LED_GREEN_SET_STATE(state)	GPIO_WritePinOutput(LED_GREEN_GPIO_BASE, (LED_GREEN_PIN_NUMBER),state)
#define LED_BLUE_SET_STATE(state)	GPIO_WritePinOutput(LED_BLUE_GPIO_BASE, (LED_BLUE_PIN_NUMBER),state)

//Mixed colors
#define LED_YELLOW_TOGGLE()	GPIO_TogglePinsOutput(LED_RED_GPIO_BASE, (1U << LED_RED_PIN_NUMBER));\
							LED_GREEN_SET_STATE(LED_RED_GET_STATE())
#define LED_CYAN_TOGGLE()	GPIO_TogglePinsOutput(LED_GREEN_GPIO_BASE, (1U << LED_GREEN_PIN_NUMBER));\
							LED_BLUE_SET_STATE(LED_GREEN_GET_STATE())
#define LED_PURPLE_TOGGLE()	GPIO_TogglePinsOutput(LED_BLUE_GPIO_BASE, (1U << LED_BLUE_PIN_NUMBER));\
							LED_RED_SET_STATE(LED_BLUE_GET_STATE())
#define LED_WHITE_TOGGLE()	GPIO_TogglePinsOutput(LED_RED_GPIO_BASE, (1U << LED_RED_PIN_NUMBER));\
							LED_GREEN_SET_STATE(LED_RED_GET_STATE());\
							LED_BLUE_SET_STATE(LED_RED_GET_STATE())

extern void app_GPIO_Init(void);

#endif /* APP_GPIO_H_ */
